# GD-3. Исследование поведения пользователей
-------------------------------------------------------------------------------------------------------------------------------

### Краткое описание проекта
* Quiz Freeze - игра, сборник вопросов в различных форматах и темах, на которые игрокам нужно давать ответы. 
* Игра одиночная, то есть каждый игрок отвечает на вопросы самостоятельно.
-------------------------------------------------------------------------------------------------------------------------------
**Этапы игры**
1. Регистрация -> registration / обязательный этап
2. Старт обучения -> tutorial_start /  опциональный этап
3. Завершение обучения -> tutorial_finish / может произойти только, если обучение было начато, можно не завершать обучение
4. Выбор уровня сложности вопросов -> level_choice / обязательное событие для перехода к следующему шагу/выбору пакета вопросов
5. Выбор пакетов вопросов -> pack_choice или  training_choice / выбор бесплатного набора вопросов
6. Покупка платных пакетов вопросов ->  факт совершения оплаты за платные вопросы
-------------------------------------------------------------------------------------------------------------------------------

### Вопросы и задачи для анализа
-------------------------------------------------------------------------------------------------------------------------------
**Интересующая выборка пользователей**: *Пользователи, которые зарегистрировались в 2018 году (с 1 января по 31 декабря 2018 года включительно).*

------------------------------------------------------------------------------------------------------------------------------- 
***Вопрос 1: Зависит ли вероятность оплаты от выбранного пользователем уровня сложности?***  
    

*Результаты анализа:* ***процент оплат варьировался в зависимости от выбранного уровня сложности.***   
    
+ *Всего ***до выбора уровня сложности дошло 41.86% ( 8342 ч.) пользователей***, зарегистрировавшихся в 2018 году.*


+ ***Наиболее популярный уровень сложности*** *среди пользователей был medium_level (его выбрало более 50 % пользователей):*
   - *easy_level: 29.35% (2448 чел.)*
   - ***medium_level: 55.68% (4645 чел.)***
   - *hard_level: 14.97% (1249 чел.)*  
    
   
+ ***Наибольший процент оплат после выбора уровня*** *сложности был у пользователей группы hard_level.*
   - *easy_level 7.72% (189 чел.), средний чек: 114.95 руб.*
   - *medium_level 20.86% (969 чел.), средний чек: 109.52 руб.* 
   - ***hard_level 35.39%*** *(442 чел.), средний чек: 111.6 руб.*
-------------------------------------------------------------------------------------------------------------------------------

***Вопрос 2: Существует ли разница во времени между событиями регистрации и оплаты для разных групп пользователей с разным уровнем сложности?***



*Результаты анализа*: ***разница во времени между событиями есть, но разница показателей между группами не значительна.*** 
    
+ ***Платящие пользователи достаточно быстро переходят к выбору уровня*** *(макс показатель для всех уровней - 1 день, ***в среднем - 6-7 часов с момента регистрации***)*  
------------------------------------------------------------------------------------------------------------------------------- 
*Таблица: Разница во времени между регистрацией и выбором уровня у платящих пользователей (в зависимости от выбранного уровня)*

|level                                        | easy          | hard         |medium         |
|:------------------------------------------  |:-------------:|:------------:|:-------------:|
|платящие пользователи в группе               | 189           |442           |969            |
|**среднее время между регистрацией и выбором уровня** | **0 дн 07 ч 11 м**  | **0 дн 07 ч 34 м**| **0 дн 06 ч 57 м** |
|стандартное отклонение в группе             | 0 дн 04 ч 52 м  | 0 дн 04 ч 42 м | 0 дн 04 ч 31 м  |
|мин. время между регистрацией и выбором уровня       | 0 дн 00 ч 46 м  | 0 дн 00 ч 19 м | 0 дн 00 ч 14 м  |
|25% перцентиль                             | 0 дн 0 ч 48 м  | 0 дн 04 ч 11 м | 0 дн 03 ч 39 м  |
|**50% (медиана)**                                | **0 дн 05 ч 47 м** | **0 дн 06 ч 30 м** | **0 дн 05 ч 51 м** |
|75% перцентиль                             | 0 дн 09 ч 31 м  | 0 дн 10 ч 22 м | 0 дн 09 ч 32 м |
|макс. время между регистрацией и выбором уровня    | 1 дн 00 ч 55 м | 1 дн 03 ч 14 м | 1 дн 01 ч 01 м | 

-------------------------------------------------------------------------------------------------------------------------------

+ ***Разница между выбором уровня и оплатой в среднем составляет 3 дня для всех групп пользователей*** 
    *(по максимальным показателям - наиболее быстрыми являются пользователи hard_level (максимальная длительность между выбором уровня и оплатой составляет 8 дней, у остальных групп - макс 10 дней)*  
-------------------------------------------------------------------------------------------------------------------------------

*Таблица: Разница во времени между выбором уровня и оплатой для разных групп пользователей (в зависимости от выбранного уровня)*
    
|level                                        | easy          | hard         |medium         |
|:------------------------------------------  |:-------------:|:------------:|:-------------:|
|платящие пользователи в группе               | 189           |442           |969            |
|**среднее время между выбором уровня и оплатой** | **3 дн 14 ч 58 м**  | **3 дн 07 ч 20 м**| **3 дн 23 ч 14 м** |
|стандартное отклонение в группе             | 2 дн 07 ч 06 м  | 1 дн 21 ч 43 м | 2 дн 06 ч 18 м  |
|мин. время между выбором уровня и оплатой       | 0 дн 00 ч 49 м  | 0 дн 03ч 26 м | 0 дн 04 ч 18 м  |
|25% перцентиль                             | 1 дн 17 ч 18 м  | 1 дн 14 ч 57 м | 2 дн 01 ч 20 м  |
|**50% (медиана)**                                | **3 дн 06 ч 03 м** | **3 дн 03 ч 13 м** | **3 дн 19 ч 53 м** |
|75% перцентиль                             | 5 дн 06 ч 58 м  | 4 дн 19 ч 16 м | 5 дн 16 ч 07 м  |
|макс. время между выбором уровня и оплатой    | 10 дн 18 ч 35 м | 8 дн 01 ч 18 м | 10 дн 13 ч 51 м |

+ ***Разница между регистрацией и оплатой практически идентична разнице между выбором уровня и оплатой*** *(различие всего в несколько часов).*    
-------------------------------------------------------------------------------------------------------------------------------
*Таблица: Разница во времени между регистрацией и оплатой для разных групп пользователей (в зависимости от выбранного уровня)*
    
|level                                        | easy          | hard         |medium         |
|:------------------------------------------  |:-------------:|:------------:|:-------------:|
|платящие пользователи в группе               | 189           |442           |969            |
|**среднее время между регистрацией и оплатой** | **3 дн 22 ч 10 м**  | **3 дн 14 ч 55 м**| **4 дн 06 ч 12 м** |
|стандартное отклонение в группе             | 2 дн 07 ч 14 м  | 1 дн 22 ч 22 м | 2 дн 06 ч 25 м |
|мин. время между регистрацией и оплатой       | 0 дн 04 ч 36 м | 0 дн 09 ч 41 м | 0 дн 08 ч 39 м |
|25% перцентиль                             | 2 дн 01 ч 12 м | 1 дн 23 ч 36 м | 2 дн 08 ч 46 м  |
|**50% (медиана)**                                | **3 дн 11 ч 00 м** | **3 дн 10 ч 10 м** | **4 дн 03 ч 35 м** |
|75% перцентиль                             | 5 дн 10 ч 24 м | 5 дн 03 ч 30 м | 5 дн 23 ч 51 м  |
|макс. время  между регистрацией и оплатой    | 11 дн 00 ч 35 м | 8 дн 14 ч 21 м | 10 дн 20 ч 34 м |  

-------------------------------------------------------------------------------------------------------------------------------

### Обработка данных и расчетная часть       
-------------------------------------------------------------------------------------------------------------------------------
#### Предоставленные данные для анализа
* Таблица ***event***  содержит данные о событиях, которые совершают пользователи. Каждое событие = факт прохождения пользователем какого-либо этапа игры.
* Таблица ***purchases*** хранит данные об оплатах, которые совершают пользователи.
-------------------------------------------------------------------------------------------------------------------------------
#### Предполагаемые этапы анализа 
1. Загрузка и знакомство с данными 
2. Преобразование данных и выборка пользователей по заданным параметрам
3. Разделение выборки на сегменты -> пользователи по уровню сложности 
4. Расчет % платящих пользователей в зависимости от выбранного уровня сложности 
5. Расчет разницы во времени между регистрацией и оплатой в зависимости от сегментов (п.3)
6. Проверка расчетов - суммарные данные 
7. Общие выводы - закомпоновка ответов в начало документа

### 1. Этап: загрузка и знакомство с данными

In [1]:
# импортирование библиотеки 
import pandas as pd

In [2]:
# загрузка и oзнакомление со структурой данных:
events_df = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vTcjC4Ef0GX5ZZo_OiOmpg76BBrXgvSqq9VD35maWMfxSxXw_UXnjYrHXEnv4zIlLPXx6Nh5v4KL0Lo/pub?output=csv', sep=',')
events_df.head(3)

,id,event_type,selected_level,start_time,tutorial_id,user_id
0,28903,registration,NaN,2016-05-11T23:40:55,NaN,12583
1,28904,registration,NaN,2016-05-11T23:49:58,NaN,12584
2,28905,registration,NaN,2016-05-12T00:53:07,NaN,12585

**Oписание датафрейма events_df:**
* id = идентификатор события
* event_type = тип события
* selected_level = выбранный уровень сложности обучения
* start_time = дата и время события
* tutorial_id = идентификатор обучения (этот идентификатор есть только у событий обучения)
* user_id = уникальный идентификатор пользователя приложения, который совершил событие

In [3]:
# проверка входит ли оплата в events
events_df['event_type'].unique()

array(['registration', 'tutorial_start', 'tutorial_finish',
       'level_choice', 'pack_choice'], dtype=object)

In [4]:
#  какие уровни сложности есть в игре
events_df['selected_level'].unique()

array([nan, 'hard', 'easy', 'medium'], dtype=object)

In [5]:
# загрузка и oзнакомление со структурой данных 
purchase_df = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vQoMieNu160y0dxUGEWHcyRln6RFAN-fwWolkO1Ugw40wsdEl0a9vFGO5kQLMLHIwG5HuLCizD3v6A0/pub?output=csv')
purchase_df.head(3)

      id  user_id       event_datetime  amount
0  15674    12584  2016-05-12T10:34:16     100
1  15675    12985  2016-05-13T08:25:56      50
2  15676    12828  2016-05-13T16:33:46      50

**Описание датафрейма purchase_df:**
* id = идентификатор события
* user_id = уникальный идентификатор пользователя приложения, который совершил событие
* event_datetime = дата и время события/покупки
* amount = сумма оплаты

Что пока видно?

- дату нужно будет преобразовать в 2-х датафреймах
- сделать фильтр по заданию (только пользователи, зарегистрировавшиеся с 01.01 по 31.12.2018)
- сузить данные в обоих датафреймах с учётом фильтра 
- подумать как будем объединять, если будем с purchase_df - возможно, стоит добавить столбец purchase в purchase_df -> в events его нет 
- посмотреть уровни сложности в игре с учётом фильтра - есть незаполненные данные, посмотреть уберутся ли они после фильтрации

### 2. Этап: преобразование данных и выборка пользователей по заданным параметрам

In [6]:
# пробуем настроить фильтрацию по дате регистрации - прописываем условия
condition_1 = (events_df['event_type'] == 'registration') # выбрать только регистрацию
condition_2 = (events_df['start_time'] >= '2018-01-01') # начиная от даты
condition_3 = (events_df['start_time'] < '2019-01-01') # заканчивая датой 31-12-2018
cond = condition_1 & condition_2 & condition_3 # объединение условий для фильтровки

In [7]:
# множество user_id, которые были зарегистрированы в интересующий период
user_id_group = set(events_df[cond]['user_id'])

In [8]:
# фильтровка только интересующих нас пользователей
events_df = events_df[events_df['user_id'].isin(user_id_group)]
purchase_df = purchase_df[purchase_df['user_id'].isin(user_id_group)]

In [9]:
# преобразовываем даты в нужный формат
events_df['start_time'] = pd.to_datetime(events_df['start_time'])
purchase_df['event_datetime'] = pd.to_datetime(purchase_df['event_datetime'])

In [10]:
# добавим в purchase_df тип события (пригодится при объединении)
purchase_df['event_type'] = 'purchase'

In [11]:
# переименуем столбцы, чтобы не путать с датами событий и оплат
events_df = events_df.rename(columns={'id':'event_id'})
events_df = events_df.rename(columns={'start_time':'event_time'})
purchase_df = purchase_df.rename(columns={'id':'purchase_id'})
purchase_df = purchase_df.rename(columns={'event_datetime':'payment_time'})

In [12]:
# oбъединение датафреймов
total_events_df = pd.concat([events_df, purchase_df], sort=False)
total_events_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 68559 entries, 51405 to 2778
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   event_id        66959 non-null  float64
 1   event_type      68559 non-null  object
 2   selected_level  8342 non-null   object
 3   event_time      66959 non-null  datetime64[ns]
 4   tutorial_id     32954 non-null  float64
 5   user_id         68559 non-null  int64
 6   purchase_id     1600 non-null   float64
 7   payment_time    1600 non-null   datetime64[ns]
 8   amount          1600 non-null   float64
dtypes: datetime64[ns](2), float64(4), int64(1), object(2)
memory usage: 5.2+ MB

### 3. Этап: разделение выборки на сегменты - группы пользователей по уровню сложности

In [13]:
# содержание значений по уровню сложности
total_events_df['selected_level'].unique()

array([nan, 'medium', 'hard', 'easy'], dtype=object)

In [14]:
# создание множества без пропущенных значений 
level_choice = set(x for x in set(total_events_df['selected_level']) if pd.isnull(x) == False)
display(level_choice)

{'easy', 'hard', 'medium'}

In [15]:
# есть ли пользователи, которые совершили выбор уровня сложности более 1 раза
user = total_events_df[(total_events_df['selected_level'].isin(level_choice))]
user = user.groupby(['user_id'])
user['selected_level'].value_counts().mean()
# среднее значение равно 1, т.е. пользователи, которые выбрали сложность более 1 раза отсутствуют

1.0

In [16]:
# делаем разделение пользователей исходя из выбранного уровня сложности ('easy', 'medium', 'hard')
easy_users_id = set (total_events_df[total_events_df['selected_level'] == 'easy']['user_id']) 
medium_users_id = set (total_events_df[total_events_df['selected_level'] == 'medium']['user_id']) 
hard_users_id = set (total_events_df[total_events_df['selected_level'] == 'hard']['user_id'])

In [17]:
# проверяем все ли пользователи, которые выбрали уровень сложности, включены в выборку
len (easy_users_id)+len(medium_users_id)+len(hard_users_id) == total_events_df[total_events_df['selected_level'].isin(level_choice)]['user_id'].nunique()
# вроде, всё верно (8342 == 8342)

True

In [19]:
# интересно посмотреть соотношение сколько всего зарегистрированных пользователей доходят до выбора
# % выбора уровня сложности 
per_who_selected_level= total_events_df[total_events_df['selected_level'].isin(level_choice)]['user_id'].nunique()/total_events_df['user_id'].nunique()
number_who_selected_level = total_events_df[total_events_df['selected_level'].isin(level_choice)]['user_id'].nunique()
easy_level = len(easy_users_id)/number_who_selected_level
medium_level=len(medium_users_id)/number_who_selected_level
hard_level= len(hard_users_id)/ number_who_selected_level
print ('Процент пользователей, которые дошли до выбора уровня сложности: {:.2%} ({} чел.)'.format(per_who_selected_level,number_who_selected_level))
print ()
print ('Разделение предпочтений по уровню сложности:')
print ('   ---> easy_level: {:.2%} ({} чел.)'. format(easy_level, len(easy_users_id)))
print ('   ---> medium_level: {:.2%} ({} чел.) <--- наиболее популярный уровень сложности'. format(medium_level, len(medium_users_id)))
print ('   ---> hard_level: {:.2%} ({} чел.)'. format(hard_level, len(hard_users_id)))

Процент пользователей, которые дошли до выбора уровня сложности: 41.86% (8342 чел.)

Разделение предпочтений по уровню сложности:
   ---> easy_level: 29.35% (2448 чел.)
   ---> medium_level: 55.68% (4645 чел.) <--- наиболее популярный уровень сложности
   ---> hard_level: 14.97% (1249 чел.)

### 4. Этап: расчет % платящих пользователей в зависимости от выбранного уровня сложности

In [20]:
# смотрим сколько пользователей перешли к оплате:
purchase_df_easy = purchase_df[purchase_df['user_id'].isin(easy_users_id)]
purchase_df_medium = purchase_df[purchase_df['user_id'].isin(medium_users_id)]
purchase_df_hard = purchase_df[purchase_df['user_id'].isin(hard_users_id)]

# расчет процентa платящих пользователей в зависимости от выбранного уровня сложности:
easy_payment = purchase_df_easy['user_id'].nunique()/len(easy_users_id)
medium_payment = purchase_df_medium['user_id'].nunique()/len(medium_users_id)
hard_payment = purchase_df_hard['user_id'].nunique()/len(hard_users_id)

In [21]:
# средний чек по группам
easy_mean=round(purchase_df_easy['amount'].mean(),2)
medium_mean=round(purchase_df_medium['amount'].mean(),2)
hard_mean=round(purchase_df_hard['amount'].mean(),2)

In [22]:
print ('Платящие пользователи после выбранного уровня сложности:')
print ()
print ('--> easy_level {:.2%} /{} чел., средний чек: {} руб.'. format(easy_payment,purchase_df_easy['user_id'].nunique(), easy_mean))
print ('-->  medium_level {:.2%} / {} чел., средний чек: {} руб. <---'. format(medium_payment, purchase_df_medium['user_id'].nunique(), medium_mean))
print ('-->  hard_level {:.2%} / {} чел., средний чек: {} руб. <-- наибольший процент оплат после выбора уровня сложности'. format(hard_payment, purchase_df_hard['user_id'].nunique(), hard_mean))

Платящие пользователи после выбранного уровня сложности:

--> easy_level 7.72% /189 чел., средний чек: 114.95 руб.
-->  medium_level 20.86% / 969 чел., средний чек: 109.52 руб. <---
-->  hard_level 35.39% / 442 чел., средний чек: 111.6 руб. <-- наибольший процент оплат после выбора уровня сложности

### 5. Этап: расчет разницы во времени между регистрацией и оплатой в зависимости от сегментов (п.3)

In [23]:
# напишем условие для фильтрации user_id по по уровню сложности и дате регистрации пользователя
easy_registration_df = total_events_df[(total_events_df['event_type'] == 'registration') & (total_events_df['user_id'].isin(easy_users_id))][['user_id','event_time']]
easy_registration_df = easy_registration_df.rename(columns={'event_time':'registration_time'})

medium_registration_df = total_events_df[(total_events_df['event_type'] == 'registration') & (total_events_df['user_id'].isin(medium_users_id))][['user_id','event_time']]
medium_registration_df = medium_registration_df.rename(columns={'event_time':'registration_time'})

hard_registration_df = total_events_df[(total_events_df['event_type'] == 'registration') & (total_events_df['user_id'].isin(hard_users_id))][['user_id','event_time']]
hard_registration_df = hard_registration_df.rename(columns={'event_time':'registration_time'})

In [24]:
# напишем условие для фильтрации user_id по уровню сложности и дате оплаты
easy_purchase_df = purchase_df[(purchase_df['user_id'].isin(easy_users_id))][['user_id', 'payment_time']]
medium_purchase_df = purchase_df[(purchase_df['user_id'].isin(medium_users_id))][['user_id', 'payment_time']]
hard_purchase_df = purchase_df[(purchase_df['user_id'].isin(hard_users_id))][['user_id', 'payment_time']]

In [27]:
# объединим датафреймы по user_id
easy_reg_and_purchase_df = easy_registration_df.merge(easy_purchase_df, on =['user_id'], how ='inner')
medium_reg_and_purchase_df = medium_registration_df.merge(medium_purchase_df, on =['user_id'], how ='inner')
hard_reg_and_purchase_df = hard_registration_df.merge(hard_purchase_df, on =['user_id'], how ='inner')

In [28]:
# рассчитаем разницу во времени между регистрацией и оплатой для каждой группы пользователей
easy_reg_and_purchase_df['timedelta_reg_to_payment'] = easy_reg_and_purchase_df['payment_time'] - easy_reg_and_purchase_df ['registration_time']
easy_reg_and_purchase_df['level'] = 'easy' #дополним столбец с уровнем сложности для последующего объединения


medium_reg_and_purchase_df['timedelta_reg_to_payment'] = medium_reg_and_purchase_df['payment_time'] - medium_reg_and_purchase_df ['registration_time']
medium_reg_and_purchase_df['level'] = 'medium'

hard_reg_and_purchase_df['timedelta_reg_to_payment'] = hard_reg_and_purchase_df['payment_time'] - hard_reg_and_purchase_df ['registration_time']
hard_reg_and_purchase_df['level'] = 'hard'

#  объединим дата фреймы для удобности отображения мин, макс, среднего и медианы 
total_by_level_df= pd.concat([easy_reg_and_purchase_df,medium_reg_and_purchase_df,hard_reg_and_purchase_df], ignore_index=True)

# выведем статистические показатели для каждой группы (для удобства перевернем столбцы)
total_by_level_df.groupby(by= ['level'])['timedelta_reg_to_payment'].describe().T

level,easy,hard,medium
count,189,442,969
mean,3 days 22:10:23.211640211,3 days 14:55:19.257918552,4 days 06:12:06.576883384
std,2 days 07:14:41.062010764,1 days 22:22:52.441896774,2 days 06:25:57.480868026
min,0 days 04:36:58,0 days 09:41:39,0 days 08:39:24
25%,2 days 01:12:12,1 days 23:36:25.500000,2 days 08:46:51
50%,3 days 11:00:23,3 days 10:10:04.500000,4 days 03:35:26
75%,5 days 10:24:59,5 days 03:30:07.750000,5 days 23:51:27
max,11 days 00:35:04,8 days 14:21:29,10 days 20:34:02

### 6. Этап: расчет разницы во времени между выбором уровня и оплатой в зависимости от сегментов

In [29]:
# напишем условие для фильтрации user_id по уровню сложности и дате выбора уровня сложности

easy_select_df = total_events_df[(total_events_df['selected_level'] == 'easy') & (total_events_df['user_id'].isin(easy_users_id))][['user_id','event_time']]
medium_select_df = total_events_df[(total_events_df['selected_level'] == 'medium') & (total_events_df['user_id'].isin(medium_users_id))][['user_id','event_time']]
hard_select_df = total_events_df[(total_events_df['selected_level'] == 'hard') & (total_events_df['user_id'].isin(hard_users_id))][['user_id','event_time']]

In [30]:
# объединим датафреймы по user_id (дата выбора уровня + дата оплаты)

easy_select_and_purchase_df = easy_select_df.merge(easy_purchase_df, on ='user_id', how = 'inner')
medium_select_and_purchase_df = medium_select_df.merge(medium_purchase_df, on ='user_id', how = 'inner')
hard_select_and_purchase_df = hard_select_df.merge(hard_purchase_df, on ='user_id', how = 'inner')

In [31]:
# рассчитаем разницу во времени для каждой группы пользователей
easy_select_and_purchase_df['timedelta_select_payment'] = easy_select_and_purchase_df['payment_time'] - easy_select_and_purchase_df['event_time']
easy_select_and_purchase_df['level'] = 'easy'

medium_select_and_purchase_df['timedelta_select_payment'] = medium_select_and_purchase_df['payment_time'] - medium_select_and_purchase_df['event_time']
medium_select_and_purchase_df['level'] = 'medium'


hard_select_and_purchase_df['timedelta_select_payment'] = hard_select_and_purchase_df['payment_time'] - hard_select_and_purchase_df['event_time']
hard_select_and_purchase_df['level'] = 'hard'

# объединим датафреймы и сгруппируем для более удобного отображения показателей

total_differ_between_level_and_payment_df = pd.concat([easy_select_and_purchase_df, medium_select_and_purchase_df, hard_select_and_purchase_df], ignore_index = True)
total_differ_between_level_and_payment_df.groupby(by= ['level'])['timedelta_select_payment'].describe().T

level,easy,hard,medium
count,189,442,969
mean,3 days 14:58:52.941798941,3 days 07:20:41.420814479,3 days 23:14:13.165118679
std,2 days 07:06:35.644097504,1 days 21:43:52.953292605,2 days 06:18:57.618467109
min,0 days 00:49:20,0 days 03:26:45,0 days 04:18:12
25%,1 days 17:18:56,1 days 14:57:23.500000,2 days 01:20:07
50%,3 days 06:03:50,3 days 03:13:57.500000,3 days 19:53:19
75%,5 days 06:58:18,4 days 19:16:00.250000,5 days 16:07:19
max,10 days 18:35:09,8 days 01:18:13,10 days 13:51:01

In [32]:
## Проверочные расчеты (регистрация и выбор уровня платящих пользователей)
easy_reg_and_select_df = easy_reg_and_purchase_df.merge(easy_select_df, on ='user_id', how ='inner')
easy_reg_and_select_df ['timedelta_reg_to_select'] = easy_reg_and_select_df['event_time'] - easy_reg_and_select_df ['registration_time']
easy_reg_and_select_df ['timedelta_select_to_payment'] = easy_reg_and_select_df['payment_time'] - easy_reg_and_select_df ['event_time']
easy_reg_and_select_df.head()

medium_reg_and_select_df = medium_reg_and_purchase_df.merge(medium_select_df, on ='user_id', how ='inner')
medium_reg_and_select_df ['timedelta_reg_to_select'] = medium_reg_and_select_df['event_time'] - medium_reg_and_select_df ['registration_time']
medium_reg_and_select_df ['timedelta_select_to_payment'] = medium_reg_and_select_df['payment_time'] - medium_reg_and_select_df ['event_time']
medium_reg_and_select_df.head()


hard_reg_and_select_df = hard_reg_and_purchase_df.merge(hard_select_df, on ='user_id', how ='inner')
hard_reg_and_select_df ['timedelta_reg_to_select'] = hard_reg_and_select_df['event_time'] - hard_reg_and_select_df ['registration_time']
hard_reg_and_select_df ['timedelta_select_to_payment'] = hard_reg_and_select_df['payment_time'] - hard_reg_and_select_df ['event_time']
hard_reg_and_select_df.head()

total_reg_select_payment_df = pd.concat([easy_reg_and_select_df, medium_reg_and_select_df, hard_reg_and_select_df])

t=total_reg_select_payment_df.groupby (by = ['level']).describe().T
print ('Проверочная таблица по показателям разницы во времени, для пользователей перешедших к оплате после выбора уровня сложности')
t[8:] #уберем вывод user_id - он здесь не нужен

Проверочная таблица по показателям разницы во времени, для пользовтелей перешедших к оплате после выбора уровня сложности

level                                                   easy  \
timedelta_reg_to_payment    count                        189
                            mean   3 days 22:10:23.211640211
                            std    2 days 07:14:41.062010764
                            min              0 days 04:36:58
                            25%              2 days 01:12:12
                            50%              3 days 11:00:23
                            75%              5 days 10:24:59
                            max             11 days 00:35:04
timedelta_reg_to_select     count                        189
                            mean   0 days 07:11:30.269841269
                            std    0 days 04:52:54.281963365
                            min              0 days 00:46:35
                            25%              0 days 03:48:51
                            50%              0 days 05:47:23
                            75%              0 days 09:31:41
                            max              1 days 00:55:34
timedelta_select_to_payment count                        189
                            mean   3 days 14:58:52.941798941
                            std    2 days 07:06:35.644097504
                            min              0 days 00:49:20
                            25%              1 days 17:18:56
                            50%              3 days 06:03:50
                            75%              5 days 06:58:18
                            max             10 days 18:35:09

level                                                   hard  \
timedelta_reg_to_payment    count                        442
                            mean   3 days 14:55:19.257918552
                            std    1 days 22:22:52.441896774
                            min              0 days 09:41:39
                            25%       1 days 23:36:25.500000
                            50%       3 days 10:10:04.500000
                            75%       5 days 03:30:07.750000
                            max              8 days 14:21:29
timedelta_reg_to_select     count                        442
                            mean   0 days 07:34:37.837104072
                            std    0 days 04:42:29.734822792
                            min              0 days 00:19:26
                            25%              0 days 04:11:26
                            50%       0 days 06:30:27.500000
                            75%              0 days 10:22:03
                            max              1 days 03:14:27
timedelta_select_to_payment count                        442
                            mean   3 days 07:20:41.420814479
                            std    1 days 21:43:52.953292605
                            min              0 days 03:26:45
                            25%       1 days 14:57:23.500000
                            50%       3 days 03:13:57.500000
                            75%       4 days 19:16:00.250000
                            max              8 days 01:18:13

level                                                 medium
timedelta_reg_to_payment    count                        969
                            mean   4 days 06:12:06.576883384
                            std    2 days 06:25:57.480868026
                            min              0 days 08:39:24
                            25%              2 days 08:46:51
                            50%              4 days 03:35:26
                            75%              5 days 23:51:27
                            max             10 days 20:34:02
timedelta_reg_to_select     count                        969
                            mean   0 days 06:57:53.411764705
                            std    0 days 04:31:41.129023817
                            min              0 days 00:14:20
                            25%              0 days 03:39:23
                            50%              0 days 05:51:34
                            75%              0 days 09:32:09
                            max              1 days 01:01:10
timedelta_select_to_payment count                        969
                            mean   3 days 23:14:13.165118679
                            std    2 days 06:18:57.618467109
                            min              0 days 04:18:12
                            25%              2 days 01:20:07
                            50%              3 days 19:53:19
                            75%              5 days 16:07:19
                            max             10 days 13:51:01

In [ ]:
#Дополним + оформим выводы в начало документа -> ответы даны сразу под вопросами в начале документа